// Fichier généré par l'admin — publie-1783546983319
const SERVICES = [{"slug":"creative-direction-curation","label":"Creative Direction & Curation"},{"slug":"special-projects-events","label":"Special Projects & Events"},{"slug":"production","label":"Production"}];
const CLIENTS = [{"slug":"airbnb","label":"Airbnb"},{"slug":"anita-dongre","label":"Anita Dongre"},{"slug":"dior","label":"Dior"},{"slug":"don-julio","label":"Don Julio"},{"slug":"ecru","label":"Ecru"},{"slug":"magna-presse","label":"Magna Presse"},{"slug":"marie-helene-de-taillac","label":"Marie-Hélène de Taillac"},{"slug":"officine-universelle-buly","label":"Officine Universelle Buly"},{"slug":"pucci","label":"Pucci"},{"slug":"the-palace-atelier","label":"The Palace Atelier"},{"slug":"the-pdkf-store","label":"The PDKF Store"}];
const PROJECTS = [
  {"id":"mariage-paris-2024","service":"special-projects-events","client":null,"title":["Mariage privé","Paris — Avril 2024"],"images":["assets/img/weddings/weddings-01.jpg","assets/img/weddings/weddings-02.jpg","assets/img/weddings/weddings-03.jpg","assets/img/weddings/weddings-04.jpg","assets/img/weddings/weddings-05.jpg","assets/img/weddings/weddings-06.jpg","assets/img/weddings/weddings-07.jpg","assets/img/weddings/weddings-08.jpg","assets/img/weddings/weddings-09.jpg","assets/img/weddings/weddings-10.jpg","assets/img/weddings/weddings-11.jpg","assets/img/weddings/weddings-12.jpg","assets/img/weddings/weddings-13.jpg","assets/img/weddings/weddings-14.jpg","assets/img/weddings/weddings-15.jpg","assets/img/weddings/weddings-16.jpg","assets/img/weddings/weddings-17.jpg","assets/img/weddings/weddings-18.jpg","assets/img/weddings/weddings-19.jpg","assets/img/weddings/weddings-20.jpg","assets/img/weddings/weddings-21.jpg","assets/img/weddings/weddings-22.jpg","assets/img/weddings/weddings-23.jpg","assets/img/weddings/weddings-24.jpg","assets/img/weddings/weddings-25.jpg","assets/img/weddings/weddings-26.jpg","assets/img/weddings/weddings-27.jpg","assets/img/weddings/weddings-28.jpg","assets/img/weddings/weddings-29.jpg"]},
  {"id":"holi-jaipur-2023","service":"special-projects-events","client":null,"title":["Fête de Holi","Jaipur — Mars 2023"],"images":["assets/img/parties/parties-01.jpg","assets/img/parties/parties-02.jpg","assets/img/parties/parties-03.jpg","assets/img/parties/parties-04.jpg","assets/img/parties/parties-05.jpg","assets/img/parties/parties-06.jpg","assets/img/parties/parties-07.jpg"]},
  {"id":"don-julio-la-fantaisie-2025","service":"special-projects-events","client":"don-julio","title":["Don Julio","Hôtel La Fantaisie","Paris — Juin 2025"],"images":["assets/img/parties/parties-08.jpg","assets/img/parties/parties-09.jpg","assets/img/parties/parties-10.jpg","assets/img/parties/parties-11.jpg","assets/img/parties/parties-12.jpg","assets/img/parties/parties-13.jpg","assets/img/parties/parties-14.jpg","assets/img/parties/parties-22.jpg","assets/img/parties/parties-23.jpg","assets/img/parties/parties-24.jpg","assets/img/parties/parties-25.jpg","assets/img/parties/parties-26.jpg"]},
  {"id":"mariage-jaipur-2019","service":"special-projects-events","client":null,"title":["Mariage privé","Jaipur — 2019"],"images":["assets/img/parties/parties-15.jpg","assets/img/parties/parties-16.jpg","assets/img/parties/parties-17.jpg","assets/img/parties/parties-18.jpg","assets/img/parties/parties-19.jpg","assets/img/parties/parties-20.jpg","assets/img/parties/parties-21.jpg"]},
  {"id":"pucci-showroom-fw23","service":"production","client":"pucci","title":["Pucci","Showroom FW23","Milan"],"images":["assets/img/scenography/scenography-01.jpg","assets/img/scenography/scenography-02.jpg","assets/img/scenography/scenography-03.jpg","assets/img/scenography/scenography-04.jpg","assets/img/scenography/scenography-05.jpg","assets/img/scenography/scenography-06.jpg"]},
  {"id":"pucci-showroom-fw24","service":"production","client":"pucci","title":["Pucci","Showroom FW24","Milan"],"images":["assets/img/scenography/scenography-07.jpg","assets/img/scenography/scenography-08.jpg","assets/img/scenography/scenography-09.jpg","assets/img/scenography/scenography-10.jpg","assets/img/scenography/scenography-11.jpg","assets/img/scenography/scenography-12.jpg"]},
  {"id":"magna-presse-press-day-2024","service":"production","client":"magna-presse","title":["Magna Presse","Press Day","Paris — Décembre 2024"],"images":["assets/img/scenography/scenography-13.jpg","assets/img/scenography/scenography-14.jpg","assets/img/scenography/scenography-15.jpg","assets/img/scenography/scenography-16.jpg","assets/img/scenography/scenography-17.jpg","assets/img/scenography/scenography-18.jpg"]},
  {"id":"pucci-showroom-2025","service":"production","client":"pucci","title":["Pucci","Showroom","Milan — Mars 2025"],"images":["assets/img/scenography/scenography-19.jpg","assets/img/scenography/scenography-20.jpg","assets/img/scenography/scenography-21.jpg","assets/img/scenography/scenography-22.jpg","assets/img/scenography/scenography-23.jpg","assets/img/scenography/scenography-24.jpg"]},
  {"id":"the-palace-atelier-jaipur","service":"creative-direction-curation","client":"the-palace-atelier","title":["The Palace Atelier","Décoration intérieure","Jaipur"],"images":["assets/img/interiors/interiors-01.jpg","assets/img/interiors/interiors-02.jpg","assets/img/interiors/interiors-03.jpg","assets/img/interiors/interiors-04.jpg","assets/img/interiors/interiors-05.jpg","assets/img/interiors/interiors-06.jpg","assets/img/interiors/interiors-19.jpg","assets/img/interiors/interiors-20.jpg","assets/img/interiors/interiors-21.jpg"]},
  {"id":"city-palace-jaipur-airbnb","service":"creative-direction-curation","client":"airbnb","title":["City Palace Jaipur","Airbnb","Décoration intérieure"],"images":["assets/img/interiors/interiors-07.jpg","assets/img/interiors/interiors-08.jpg","assets/img/interiors/interiors-09.jpg","assets/img/interiors/interiors-10.jpg","assets/img/interiors/interiors-11.jpg","assets/img/interiors/interiors-12.jpg","assets/img/interiors/interiors-13.jpg","assets/img/interiors/interiors-14.jpg","assets/img/interiors/interiors-15.jpg","assets/img/interiors/interiors-16.jpg","assets/img/interiors/interiors-17.jpg","assets/img/interiors/interiors-18.jpg"]},
  {"id":"mht-vitrine-2023","service":"creative-direction-curation","client":"marie-helene-de-taillac","title":["Marie-Hélène de Taillac","Vitrine","Septembre 2023"],"images":["assets/img/window-display/window-display-01.jpg","assets/img/window-display/window-display-02.jpg","assets/img/window-display/window-display-03.jpg","assets/img/window-display/window-display-04.jpg","assets/img/window-display/window-display-05.jpg","assets/img/window-display/window-display-06.jpg","assets/img/window-display/window-display-07.jpg"]},
  {"id":"mht-vitrine-2022","service":"creative-direction-curation","client":"marie-helene-de-taillac","title":["Marie-Hélène de Taillac","Vitrine","Septembre 2022"],"images":["assets/img/window-display/window-display-08.jpg","assets/img/window-display/window-display-09.jpg","assets/img/window-display/window-display-10.jpg","assets/img/window-display/window-display-11.jpg","assets/img/window-display/window-display-12.jpg","assets/img/window-display/window-display-13.jpg","assets/img/window-display/window-display-14.jpg"]},
  {"id":"mht-vitrine-2016","service":"creative-direction-curation","client":"marie-helene-de-taillac","title":["Marie-Hélène de Taillac","Vitrine","Septembre 2016"],"images":["assets/img/window-display/window-display-15.jpg","assets/img/window-display/window-display-16.jpg","assets/img/window-display/window-display-17.jpg","assets/img/window-display/window-display-18.jpg","assets/img/window-display/window-display-19.jpg","assets/img/window-display/window-display-20.jpg","assets/img/window-display/window-display-21.jpg"]},
  {"id":"vitrines-a-confirmer","service":"creative-direction-curation","client":null,"title":["Vitrines","À confirmer"],"images":["assets/img/window-display/window-display-22.jpg","assets/img/window-display/window-display-23.jpg","assets/img/window-display/window-display-24.jpg","assets/img/window-display/window-display-25.jpg","assets/img/window-display/window-display-26.jpg"]},
  {"id":"set-design-a-confirmer-01","service":"creative-direction-curation","client":null,"title":["Set Design","À confirmer 01"],"images":["assets/img/set-design/set-design-01.jpg","assets/img/set-design/set-design-02.jpg","assets/img/set-design/set-design-03.jpg","assets/img/set-design/set-design-04.jpg","assets/img/set-design/set-design-05.jpg","assets/img/set-design/set-design-06.jpg"]},
  {"id":"set-design-a-confirmer-02","service":"creative-direction-curation","client":null,"title":["Set Design","À confirmer 02"],"images":["assets/img/set-design/set-design-07.jpg","assets/img/set-design/set-design-08.jpg","assets/img/set-design/set-design-09.jpg","assets/img/set-design/set-design-10.jpg","assets/img/set-design/set-design-11.jpg","assets/img/set-design/set-design-12.jpg"]},
  {"id":"set-design-a-confirmer-03","service":"creative-direction-curation","client":null,"title":["Set Design","À confirmer 03"],"images":["assets/img/set-design/set-design-13.jpg","assets/img/set-design/set-design-14.jpg","assets/img/set-design/set-design-15.jpg","assets/img/set-design/set-design-16.jpg"]}
];
