// Un objet = un projet. title = lignes affichées au survol (ex. ["Pucci", "Saison 2024", "Milan"]).
// Remplacer les regroupements/titres provisoires par les vrais projets de Claire.
const PROJECT_CATS = [{"slug": "weddings", "label": "Mariages"}, {"slug": "parties", "label": "Réceptions"}, {"slug": "scenography", "label": "Scénographie"}, {"slug": "interiors", "label": "Intérieurs"}, {"slug": "window-display", "label": "Vitrines"}, {"slug": "set-design", "label": "Set Design"}];
const PROJECTS = [
  {"id": "weddings-p01", "cat": "weddings", "title": ["Mariages", "Projet 01"], "images": ["assets/img/weddings/weddings-01.jpg", "assets/img/weddings/weddings-02.jpg", "assets/img/weddings/weddings-03.jpg", "assets/img/weddings/weddings-04.jpg", "assets/img/weddings/weddings-05.jpg", "assets/img/weddings/weddings-06.jpg"]},
  {"id": "weddings-p02", "cat": "weddings", "title": ["Mariages", "Projet 02"], "images": ["assets/img/weddings/weddings-07.jpg", "assets/img/weddings/weddings-08.jpg", "assets/img/weddings/weddings-09.jpg", "assets/img/weddings/weddings-10.jpg", "assets/img/weddings/weddings-11.jpg", "assets/img/weddings/weddings-12.jpg"]},
  {"id": "weddings-p03", "cat": "weddings", "title": ["Mariages", "Projet 03"], "images": ["assets/img/weddings/weddings-13.jpg", "assets/img/weddings/weddings-14.jpg", "assets/img/weddings/weddings-15.jpg", "assets/img/weddings/weddings-16.jpg", "assets/img/weddings/weddings-17.jpg", "assets/img/weddings/weddings-18.jpg"]},
  {"id": "weddings-p04", "cat": "weddings", "title": ["Mariages", "Projet 04"], "images": ["assets/img/weddings/weddings-19.jpg", "assets/img/weddings/weddings-20.jpg", "assets/img/weddings/weddings-21.jpg", "assets/img/weddings/weddings-22.jpg", "assets/img/weddings/weddings-23.jpg", "assets/img/weddings/weddings-24.jpg"]},
  {"id": "weddings-p05", "cat": "weddings", "title": ["Mariages", "Projet 05"], "images": ["assets/img/weddings/weddings-25.jpg", "assets/img/weddings/weddings-26.jpg", "assets/img/weddings/weddings-27.jpg", "assets/img/weddings/weddings-28.jpg", "assets/img/weddings/weddings-29.jpg"]},
  {"id": "parties-p01", "cat": "parties", "title": ["Réceptions", "Projet 01"], "images": ["assets/img/parties/parties-01.jpg", "assets/img/parties/parties-02.jpg", "assets/img/parties/parties-03.jpg", "assets/img/parties/parties-04.jpg", "assets/img/parties/parties-05.jpg", "assets/img/parties/parties-06.jpg", "assets/img/parties/parties-07.jpg"]},
  {"id": "parties-p02", "cat": "parties", "title": ["Réceptions", "Projet 02"], "images": ["assets/img/parties/parties-08.jpg", "assets/img/parties/parties-09.jpg", "assets/img/parties/parties-10.jpg", "assets/img/parties/parties-11.jpg", "assets/img/parties/parties-12.jpg", "assets/img/parties/parties-13.jpg", "assets/img/parties/parties-14.jpg"]},
  {"id": "parties-p03", "cat": "parties", "title": ["Réceptions", "Projet 03"], "images": ["assets/img/parties/parties-15.jpg", "assets/img/parties/parties-16.jpg", "assets/img/parties/parties-17.jpg", "assets/img/parties/parties-18.jpg", "assets/img/parties/parties-19.jpg", "assets/img/parties/parties-20.jpg", "assets/img/parties/parties-21.jpg"]},
  {"id": "parties-p04", "cat": "parties", "title": ["Réceptions", "Projet 04"], "images": ["assets/img/parties/parties-22.jpg", "assets/img/parties/parties-23.jpg", "assets/img/parties/parties-24.jpg", "assets/img/parties/parties-25.jpg", "assets/img/parties/parties-26.jpg"]},
  {"id": "scenography-p01", "cat": "scenography", "title": ["Scénographie", "Projet 01"], "images": ["assets/img/scenography/scenography-01.jpg", "assets/img/scenography/scenography-02.jpg", "assets/img/scenography/scenography-03.jpg", "assets/img/scenography/scenography-04.jpg", "assets/img/scenography/scenography-05.jpg", "assets/img/scenography/scenography-06.jpg"]},
  {"id": "scenography-p02", "cat": "scenography", "title": ["Scénographie", "Projet 02"], "images": ["assets/img/scenography/scenography-07.jpg", "assets/img/scenography/scenography-08.jpg", "assets/img/scenography/scenography-09.jpg", "assets/img/scenography/scenography-10.jpg", "assets/img/scenography/scenography-11.jpg", "assets/img/scenography/scenography-12.jpg"]},
  {"id": "scenography-p03", "cat": "scenography", "title": ["Scénographie", "Projet 03"], "images": ["assets/img/scenography/scenography-13.jpg", "assets/img/scenography/scenography-14.jpg", "assets/img/scenography/scenography-15.jpg", "assets/img/scenography/scenography-16.jpg", "assets/img/scenography/scenography-17.jpg", "assets/img/scenography/scenography-18.jpg"]},
  {"id": "scenography-p04", "cat": "scenography", "title": ["Scénographie", "Projet 04"], "images": ["assets/img/scenography/scenography-19.jpg", "assets/img/scenography/scenography-20.jpg", "assets/img/scenography/scenography-21.jpg", "assets/img/scenography/scenography-22.jpg", "assets/img/scenography/scenography-23.jpg", "assets/img/scenography/scenography-24.jpg"]},
  {"id": "interiors-p01", "cat": "interiors", "title": ["Intérieurs", "Projet 01"], "images": ["assets/img/interiors/interiors-01.jpg", "assets/img/interiors/interiors-02.jpg", "assets/img/interiors/interiors-03.jpg", "assets/img/interiors/interiors-04.jpg", "assets/img/interiors/interiors-05.jpg", "assets/img/interiors/interiors-06.jpg"]},
  {"id": "interiors-p02", "cat": "interiors", "title": ["Intérieurs", "Projet 02"], "images": ["assets/img/interiors/interiors-07.jpg", "assets/img/interiors/interiors-08.jpg", "assets/img/interiors/interiors-09.jpg", "assets/img/interiors/interiors-10.jpg", "assets/img/interiors/interiors-11.jpg", "assets/img/interiors/interiors-12.jpg"]},
  {"id": "interiors-p03", "cat": "interiors", "title": ["Intérieurs", "Projet 03"], "images": ["assets/img/interiors/interiors-13.jpg", "assets/img/interiors/interiors-14.jpg", "assets/img/interiors/interiors-15.jpg", "assets/img/interiors/interiors-16.jpg", "assets/img/interiors/interiors-17.jpg", "assets/img/interiors/interiors-18.jpg"]},
  {"id": "interiors-p04", "cat": "interiors", "title": ["Intérieurs", "Projet 04"], "images": ["assets/img/interiors/interiors-19.jpg", "assets/img/interiors/interiors-20.jpg", "assets/img/interiors/interiors-21.jpg"]},
  {"id": "window-display-p01", "cat": "window-display", "title": ["Vitrines", "Projet 01"], "images": ["assets/img/window-display/window-display-01.jpg", "assets/img/window-display/window-display-02.jpg", "assets/img/window-display/window-display-03.jpg", "assets/img/window-display/window-display-04.jpg", "assets/img/window-display/window-display-05.jpg", "assets/img/window-display/window-display-06.jpg", "assets/img/window-display/window-display-07.jpg"]},
  {"id": "window-display-p02", "cat": "window-display", "title": ["Vitrines", "Projet 02"], "images": ["assets/img/window-display/window-display-08.jpg", "assets/img/window-display/window-display-09.jpg", "assets/img/window-display/window-display-10.jpg", "assets/img/window-display/window-display-11.jpg", "assets/img/window-display/window-display-12.jpg", "assets/img/window-display/window-display-13.jpg", "assets/img/window-display/window-display-14.jpg"]},
  {"id": "window-display-p03", "cat": "window-display", "title": ["Vitrines", "Projet 03"], "images": ["assets/img/window-display/window-display-15.jpg", "assets/img/window-display/window-display-16.jpg", "assets/img/window-display/window-display-17.jpg", "assets/img/window-display/window-display-18.jpg", "assets/img/window-display/window-display-19.jpg", "assets/img/window-display/window-display-20.jpg", "assets/img/window-display/window-display-21.jpg"]},
  {"id": "window-display-p04", "cat": "window-display", "title": ["Vitrines", "Projet 04"], "images": ["assets/img/window-display/window-display-22.jpg", "assets/img/window-display/window-display-23.jpg", "assets/img/window-display/window-display-24.jpg", "assets/img/window-display/window-display-25.jpg", "assets/img/window-display/window-display-26.jpg"]},
  {"id": "set-design-p01", "cat": "set-design", "title": ["Set Design", "Projet 01"], "images": ["assets/img/set-design/set-design-01.jpg", "assets/img/set-design/set-design-02.jpg", "assets/img/set-design/set-design-03.jpg", "assets/img/set-design/set-design-04.jpg", "assets/img/set-design/set-design-05.jpg", "assets/img/set-design/set-design-06.jpg"]},
  {"id": "set-design-p02", "cat": "set-design", "title": ["Set Design", "Projet 02"], "images": ["assets/img/set-design/set-design-07.jpg", "assets/img/set-design/set-design-08.jpg", "assets/img/set-design/set-design-09.jpg", "assets/img/set-design/set-design-10.jpg", "assets/img/set-design/set-design-11.jpg", "assets/img/set-design/set-design-12.jpg"]},
  {"id": "set-design-p03", "cat": "set-design", "title": ["Set Design", "Projet 03"], "images": ["assets/img/set-design/set-design-13.jpg", "assets/img/set-design/set-design-14.jpg", "assets/img/set-design/set-design-15.jpg", "assets/img/set-design/set-design-16.jpg"]}
];
